language: node_js

sudo: false

node_js:
  - 12

cache:
  directories:
  - node_modules

before_install:
  - |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)|(^(docs))/'
    then
      echo "Only docs were updated, stopping build process."
      exit
    fi

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TRAVIS_TOKEN_KEY
  local_dir: Knotes
  on:
    branch: main
